---
apiVersion: v1
kind: Service
metadata:
    name: customer
    namespace: customerns
    labels:
        app: customer
spec:
    type: LoadBalancer
    selector:
        app: customer
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000

